spring.application.name=Backend

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/vibedb
spring.datasource.username=postgres
spring.datasource.password=passwort

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=8080

spring.jpa.show-sql=true
